In [5]:
import numpy as np

In [16]:
series = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [17]:
# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # Find the end of this pattern
        end_ix = i + n_steps
        # Check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i: end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [20]:
X, y = split_sequence(series, 3)

In [23]:
print("Series shape: ", series.shape)
print("X shape: ", X.shape)
print("Y shape: ", y.shape)
print("Print every sample:")
for i in range(len(X)):
    print(X[i], y[i])

Series shape:  (10,)
X shape:  (7, 3)
Y shape:  (7,)
Print every sample:
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


In [24]:
X = X.reshape(X.shape[0], X.shape[1], 1)

In [25]:
print("X shape: ", X.shape)

X shape:  (7, 3, 1)
