In [13]:
import numpy as np
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import concatenate
from keras.models import Sequential

#### Data preparation

In [4]:
# choose a number of time steps
n_steps = 3

# define input sequence
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
print("dataset: ", out_seq)

dataset:  [ 25  45  65  85 105 125 145 165 185]


In [5]:
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = np.hstack((in_seq1, in_seq2, out_seq))
print("reshaped dataset: \n", dataset)

reshaped dataset: 
 [[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [6]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [7]:
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print("X shape, y shape: ", X.shape, y.shape)
# summarize the data
print("data summary: ")
for i in range(len(X)):
    print(X[i], y[i])

X shape, y shape:  (7, 3, 2) (7,)
data summary: 
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [8]:
n_input = X.shape[1]*X.shape[2]
X = X.reshape((X.shape[0], n_input))

In [9]:
print(X)

[[10 15 20 25 30 35]
 [20 25 30 35 40 45]
 [30 35 40 45 50 55]
 [40 45 50 55 60 65]
 [50 55 60 65 70 75]
 [60 65 70 75 80 85]
 [70 75 80 85 90 95]]


#### Define model


In [14]:
multivariate_model = Sequential()
multivariate_model.add(Dense(100, activation='relu', input_dim=n_input))
multivariate_model.add(Dense(1))
multivariate_model.compile(optimizer='adam', loss='mse')

#### Fit model


In [17]:
multivariate_model.fit(X, y, epochs = 2000, verbose = 0)

#### Prediction


In [18]:
# demonstrate prediction
x_input = np.array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_input))
yhat = multivariate_model.predict(x_input, verbose=0)
print(yhat)

[[205.43578]]
