# Univariate MLP

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

2024-04-12 16:08:34.030720: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### Data preparation

In [2]:
# choose a number of time steps
n_steps = 3
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [3]:
# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # Find the end of this pattern
        end_ix = i + n_steps
        # Check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i: end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [4]:
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [6]:
print("X: \n", X)
print("y: \n", y)

X: 
 [[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
y: 
 [40 50 60 70 80 90]


#### Define model

In [10]:
univariate_model = Sequential()
univariate_model.add(Dense(100, activation='relu', input_dim=n_steps))
univariate_model.add(Dense(1))
univariate_model.compile(optimizer='adam', loss='mse')

#### Fit model

In [21]:
univariate_model.fit(X, y, epochs = 500, verbose = 0)

#### Prediction

In [23]:
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps))
yhat = univariate_model.predict(x_input, verbose = 1)
print(yhat)

1/1 [==============================] - 0s 21ms/step
[[101.919846]]
